name: Python Package

on:
  push:
  
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"

    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry install -E runtime-deps --with dev
    - run: poetry run ruff .
    - run: poetry run pytest .

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    needs: ci
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'poetry'
    - run: poetry install --without dev
    - name: Build and publish
      run: |
        poetry publish --build \
          --username ${{ secrets.PYPI_USERNAME }} \
          --password ${{ secrets.PYPI_PASSWORD }}