name: Python package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - run: poetry install -E runtime-deps --with dev
    - run: poetry run ruff .
    - run: poetry run pytest
    - name: Build and publish
      run: |
        poetry publish --build \
          --username ${{ secrets.PYPI_USERNAME }} \
          --password ${{ secrets.PYPI_PASSWORD }}